
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 12 22:17:25 CLST 2021
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Verde = 21;
  public static final int Fin = 7;
  public static final int Triangulo = 12;
  public static final int Rojo = 17;
  public static final int Cons = 16;
  public static final int Coma = 4;
  public static final int EOF = 0;
  public static final int Dibujar = 6;
  public static final int Azul = 20;
  public static final int Blanco = 19;
  public static final int Linea = 9;
  public static final int Relleno = 15;
  public static final int error = 1;
  public static final int Redondo = 11;
  public static final int Igual = 8;
  public static final int Amarillo = 18;
  public static final int ParC = 3;
  public static final int VAR = 5;
  public static final int Cuadro = 10;
  public static final int Color = 13;
  public static final int Asignar = 14;
  public static final int ParA = 2;
}

